name: Build Docker image

on: [push]

env:
  APP_IMAGE: ghcr.io/mhzrerfani/innoscripta-news-aggregator
  GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
  GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
    steps:
      # Setup
      - uses: actions/checkout@v4

      # we need to replace `/` in the branch name with `-` to make it compatible with docker registry tags
      - name: Serialize branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
        id: serialize_branch

      # Build Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.APP_IMAGE }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.APP_IMAGE }}:${{ steps.serialize_branch.outputs.branch }}
            ${{ env.APP_IMAGE }}:${{ github.sha }}
          labels: ${{ steps.serialize_branch.outputs.branch }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEWSAPI_KEY=${{ env.NEWSAPI_KEY }}
            GUARDIAN_API_KEY=${{ env.GUARDIAN_API_KEY }}
